---
title: "HW3"
format: html
editor: visual
---

```{r}
#download this file, put it in your working directory and read it in via the code below:

hw2_list <- load("hw2_list.rda")
```

```{r}
hw2_list
```

```{r}
bp_list$status <- character(20)
```

```{r}
#create a for loop - I tried running the loop below, but since I got an unexpected error, I decided to comment out the code below.

#if (post_bp <= 120) {
    #status <- "optimal"
  #} else if (120 < post_bp <= 130) {
    #status <- "borderline"
  #} else if (post_bp > 130)
    #status <- "high"
  #}
#return(status)
```

```{r}
my_list <- list(bp_list$treatment, bp_list$placebo)
```

```{r}
# in a list with two data frames in it
summarybptreatmentpreb <- summary(bp_list$treatment$pre_bp)
summarybptreatmentpostb <- summary(bp_list$treatment$post_bp)
summarybptreatmentdiffb <- summary(bp_list$treatment$diff_bp)

summarybpplacebopreb <- summary(bp_list$placebo$pre_bp)
summarybpplacebopostb <- summary(bp_list$placebo$post_bp)
summarybpplacebodiffb <- summary(bp_list$placebo$diff_bp)
```

```{r}
#finds the statistic of interest (as defined by the user input) for the pre, post, and diff columns of both data frames.
summarybptreatmentpreb <- summary(bp_list$treatment$pre_bp, get(stat))
summarybptreatmentpostb <- summary(bp_list$treatment$post_bp, get(stat))
summarybptreatmentdiffb <- summary(bp_list$treatment$diff_bp, get(stat))

summarybpplacebopreb <- summary(bp_list$placebo$pre_bp, get(stat))
summarybpplacebopostb <- summary(bp_list$placebo$post_bp, get(stat))
summarybpplacebodiffb <- summary(bp_list$placebo$diff_bp, get(stat))
```

```{r}
#assign names to the vector
#six values should then be returned as a named list with meaningful names
vector1 <- c(summarybptreatmentpreb, summarybptreatmentpostb, summarybptreatmentdiffb, summarybpplacebopreb, summarybpplacebopostb, summarybpplacebodiffb)
names(vector1) <- 1:length(vector1)
```
